# Generated by Django 6.0.4 on 2026-05-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_review_rating_alter_tour_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
